#!/bin/sh
#Usage - pp

PWD=$(basename `pwd`)

case $PWD in
	6010)
		sublime-text ~/repositories/6010/portal-impl/src/portal.properties
		;;
	6011)
		sublime-text ~/repositories/6011/portal-impl/src/portal.properties
		;;
	liferay-portal-ee-6.0.12)
		sublime-text ~/repositories/liferay-portal-ee-6.0.12/portal-impl/src/portal.properties
		;;
	liferay-portal-ee-6.0.x)
		sublime-text ~/repositories/liferay-portal-ee-6.0.x/portal-impl/src/portal.properties
		;;
	liferay-portal-ee-6.1.10)
		sublime-text ~/repositories/liferay-portal-ee-6.1.10/portal-impl/src/portal.properties
		;;
	liferay-portal-ee-6.1.20)
		sublime-text ~/repositories/liferay-portal-ee-6.1.20/portal-impl/src/portal.properties
		;;
	liferay-portal-ee-6.1.30)
		sublime-text ~/repositories/liferay-portal-ee-6.1.30/portal-impl/src/portal.properties
		;;
	liferay-portal-ee-6.1.x)
		sublime-text ~/repositories/liferay-portal-ee-6.1.x/portal-impl/src/portal.properties
		;;
	liferay-portal-ee-6.2.10)
		sublime-text ~/repositories/liferay-portal-ee-6.2.10/portal-impl/src/portal.properties
		;;
	liferay-portal-ee-6.2.x)
		sublime-text ~/repositories/liferay-portal-ee-6.2.x/portal-impl/src/portal.properties
		;;
	liferay-portal-ee-7.0.x)
		sublime-text ~/repositories/liferay-portal-ee-7.0.x/portal-impl/src/portal.properties
		;;
	liferay-portal)
		sublime-text ~/repositories/liferay-portal/portal-impl/src/portal.properties
		;;
	*)
esac