#!/bin/sh
#Usage - props

PWD=$(basename `pwd`)

case $PWD in
	6010)
		cd ~/deploy/6010
		sublime-text portal-ext.properties
		;;
	6011)
		cd ~/deploy/6011
		sublime-text portal-ext.properties
		;;
	liferay-portal-ee-6.0.12)
		cd ~/deploy/6012
		sublime-text portal-ext.properties
		;;
	liferay-portal-ee-6.0.x)
		cd ~/deploy/60x
		sublime-text portal-ext.properties
		;;
	liferay-portal-ee-6.1.10)
		cd ~/deploy/6110
		sublime-text portal-ext.properties
		;;
	liferay-portal-ee-6.1.20)
		cd ~/deploy/6120
		sublime-text portal-ext.properties
		;;
	liferay-portal-ee-6.1.30)
		cd ~/deploy/6130
		sublime-text portal-ext.properties
		;;
	liferay-portal-ee-6.1.x)
		cd ~/deploy/61x
		sublime-text portal-ext.properties
		;;
	liferay-portal-ee-6.2.10)
		cd ~/deploy/6210
		sublime-text portal-ext.properties
		;;
	liferay-portal-ee-6.2.x)
		cd ~/deploy/62x
		sublime-text portal-ext.properties
		;;
	liferay-portal-ee-7.0.x)
		cd ~/deploy/70x
		sublime-text portal-ext.properties
		;;
	liferay-portal)
		cd ~/deploy/trunk
		sublime-text portal-ext.properties
		;;
	*)
esac