#!/bin/sh
#Usage - run $VERSION_NUMBER

case $1 in
	6010)
		echo -e "\n""\033[32mRun 6010\033[0m"
		cd E:/Deploy/6010/tomcat-6.0.29/bin
		./catalina.sh jpda run
		;;
	6011)
		echo -e "\n""\033[32mRun 6011\033[0m"
		cd E:/Deploy/6011/tomcat-6.0.29/bin
		./catalina.sh jpda run
		;;
	liferay-portal-ee-6.0.12)
		echo -e "\n""\033[32mRun 6012\033[0m"
		cd E:/Deploy/6012/tomcat-6.0.32/bin
		./catalina.sh jpda run
		;;
	liferay-portal-ee-6.0.x)
		echo -e "\n""\033[32mRun 60x\033[0m"
		cd E:/Deploy/60x/tomcat-6.0.32/bin
		./catalina.sh jpda run
		;;
	liferay-portal-ee-6.1.10)
		echo -e "\n""\033[32mRun 6110\033[0m"
		cd E:/Deploy/6110/tomcat-7.0.25/bin
		./catalina.sh jpda run
		;;
	liferay-portal-ee-6.1.20)
		echo -e "\n""\033[32mRun 6120\033[0m"
		cd E:/Deploy/6120/tomcat-7.0.27/bin
		./catalina.sh jpda run
		;;
	liferay-portal-ee-6.1.x)
		echo -e "\n""\033[32mRun 61x\033[0m"
		cd E:/Deploy/61x/tomcat-7.0.27/bin
		./catalina.sh jpda run
		;;		
	liferay-portal)
		echo -e "\n""\033[32mRun Trunk\033[0m"
		cd E:/Deploy/trunk/tomcat-7.0.27/bin
		./catalina.sh jpda run
		;;
	*)
esac