<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>log</string>
	</array>
	<key>name</key>
	<string>log4j</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>(^(.+)(TRACE))</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>log4j.trace</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>match</key>
			<string>(^(.+)(DEBUG))</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>log4j.debug</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>match</key>
			<string>(^(.+)(INFO))</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>log4j.info</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>match</key>
			<string>(^(.+)(WARN)(.+)(\[)(.*)(\]\[)([^\]]*)(\]))(.+)$</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>log4j.warn</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>match</key>
			<string>(^(.+)(ERROR)(.+)(\[)(.*)(\]\[)([^\]]*)(\]))(.+)$</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>log4j.error</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>match</key>
			<string>(^(.+)(FATAL)(.+)(\[)(.*)(\]\[)([^\]]*)(\]))(.+)$</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>log4j.fatal</string>
				</dict>
			</dict>
		</dict>
	</array>
	<key>scopeName</key>
	<string>log</string>
	<key>uuid</key>
	<string>2f82de79-7495-44ff-ac2c-5e310c5dcffc</string>
</dict>
</plist>
